name: Flutter CI/CD

on:
  push:
    branches:
      - main
      - dev

jobs:

  android-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.4"
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Restore Keystore
        run: |
          mkdir -p android/app/keystore
          echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 --decode > android/app/keystore/upload-keystore.jks

      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=keystore/upload-keystore.jks" >> android/key.properties

      - name: Clean Flutter
        run: flutter clean

      - name: Build Android AppBundle
        run: flutter build appbundle --build-number ${{ github.run_number }}

      - name: Upload to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAY_STORE_JSON_KEY }}
          packageName: com.emizen.flutter_cicd_test
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          track: internal
          status: draft



  ios-build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.4"
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Install CocoaPods
        run: |
          cd ios
          pod install --repo-update

      - name: Install iOS Certificate
        run: |
          echo "${{ secrets.IOS_CERTIFICATE }}" | base64 --decode > certificate.p12
          security create-keychain -p "" build.keychain
          security import certificate.p12 \
            -k build.keychain \
            -P "${{ secrets.IOS_CERTIFICATE_PASSWORD }}" \
            -T /usr/bin/codesign
          security list-keychains -d user -s build.keychain

      - name: Install provisioning profile
        run: |
          mkdir -p "$HOME/Library/MobileDevice/Provisioning Profiles"
          echo "${{ secrets.IOS_PROVISIONING_PROFILE }}" | base64 --decode > profile.mobileprovision
          
          UUID=$(/usr/libexec/PlistBuddy -c "Print UUID" /dev/stdin <<< $(security cms -D -i profile.mobileprovision))
          cp profile.mobileprovision "$HOME/Library/MobileDevice/Provisioning Profiles/$UUID.mobileprovision"

      - name: Clean Flutter
        run: flutter clean

      - name: Build IPA
        run: |
          flutter build ipa \
            --release \
            --export-options-plist=ios/ExportOptions.plist \
            --build-name=1.0.${{ github.run_number }}

      - name: Show IPA files
        run: ls build/ios/ipa

      - name: Upload to TestFlight
        uses: apple-actions/upload-testflight-build@v1
        with:
          app-path: build/ios/ipa/*.ipa
          issuer-id: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          api-key-id: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          api-private-key: ${{ secrets.APP_STORE_CONNECT_API_KEY }}

      - name: Send success email
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_PASSWORD }}
          subject: "🚀 Flutter CI/CD Deployment Successful"
          to: shivanand@emails.emizentech.com
          from: ${{ secrets.GMAIL_USERNAME }}
          body: |
            Deployment completed successfully.

            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.sha }}
            Actor: ${{ github.actor }}

            View logs:
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Send failure email
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_PASSWORD }}
          subject: "❌ Flutter CI/CD Deployment Failed"
          to: shivanand@emails.emizentech.com
          from: ${{ secrets.GMAIL_USERNAME }}
          body: |
            Deployment FAILED.

            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.sha }}

            Check logs:
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}